### PR TITLE
transformations of x values

### PR DESCRIPTION
**Pull request by igordertigor**
We talked about this recently. Would you mind trying it out, please.

### CODE REVIEW

**Comment by igordertigor** [comment]
Tests passed on Travis but don't show up here for some reason.

**Comment by EleeStalker** [comment]
With this datafile:
```
data = np.array([[0.02, 0.5, 20]
 [0.025, 0.6, 20],
 [0.03, 0.55, 20],
 [0.04, 0.6, 20],
 [0.05, 0.65, 20],
 [0.065, 0.8, 20],
 [0.08, 0.7, 20],
 [0.1, 0.6, 20],
 [0.15, 0.8, 20],
 [0.2, 0.6, 20],
 [0.25, 0.75, 20],
 [0.275, 0.8, 20],
 [0.325, 0.9, 20],
 [0.325, 0.85, 20],
 [0.35, 0.8, 20],
 [0.35, 0.9, 20],
 [0.4, 0.8, 20],
 [0.4, 0.95, 20],
 [0.45, 0.95, 20],
 [0.5, 0.95, 20],
 [0.55, 0.7, 20]])
```
I get NaNs with the following psychometric function model
```
psychometric = pmf.PsychometricFunction(pmf.gumbel, 0.5, transform=np.log10)
```
That means that I can't plot. This worked before, when I had manually transformed the x values in the dataset like this:
```
data[:, 0] = np.log10(data[:, 0])
psychometric = pmf.PsychometricFunction(pmf.gumbel, 0.5)
```

**Comment by igordertigor** [comment]
I fixed the bug that was there.

**Review by EleeStalker — APPROVED** [review]
I tested out the new version with my data, and it's now working smoothly.

**Pull request merged**
